In [40]:
from datetime import datetime
from dateutil.relativedelta import relativedelta

import pandas as pd
pd.set_option("display.max_columns", 30)

import requests

In [41]:
current_datetime = datetime.now() - relativedelta(months=2)
forrmatted_datetime = current_datetime.strftime("%Y-%m-%d")

url =( 
    f"https://data.cityofchicago.org/resource/ajtu-isnz.json?"
    f"$where=trip_start_timestamp >= '{forrmatted_datetime}T00:00:00' "
    f"AND trip_start_timestamp <= '{forrmatted_datetime}T23:59:59' "
    f"&$limit=50000"
)
response = requests.get(url)
data = response.json()

len(data)

19310

In [42]:
taxi_trips = pd.DataFrame(data)

taxi_trips.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
0,68bfc5ca3809fb9713c19f74a21f008b0e73fc49,00c0020de20ee2cd36c1d41058360c24dad77a52639413...,2026-01-15T23:45:00.000,2026-01-16T00:15:00.000,1499,17.77,76,32,44,10.2,0,6.5,61.2,Credit Card,City Service,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",41.878865584,-87.625192142,"{'type': 'Point', 'coordinates': [-87.62519214...",NaN,NaN
1,6dfe66a61d223a34ec4d63ede02a9a01785549c5,8a0cbb4528e81a685396639a29b35d67d6d48bee0f6b96...,2026-01-15T23:45:00.000,2026-01-16T00:15:00.000,1320,15.4,56,7,38.75,5,0,4,47.75,Credit Card,Transit Administrative Center Inc,41.79259236,-87.769615453,"{'type': 'Point', 'coordinates': [-87.76961545...",41.922686284,-87.649488729,"{'type': 'Point', 'coordinates': [-87.64948872...",NaN,NaN
2,6e4174f301ac0f53b3a26cbcb744592f908217f9,78d1ae230754ef2eca7aa3e828789bc4714b8a261a35d5...,2026-01-15T23:45:00.000,2026-01-15T23:45:00.000,7,0,8,8,20,0,0,0,20,Cash,City Service,41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",NaN,NaN
3,6f588976c6c141b981a629a94b50801d38e3b6c2,c9bda81f1aaad786527911c983b6be11f28c6f46469e1a...,2026-01-15T23:45:00.000,2026-01-15T23:45:00.000,658,2.44,8,24,9.37,2.54,0,0,12.41,Mobile,Taxicab Insurance Agency Llc,41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",41.901206994,-87.676355989,"{'type': 'Point', 'coordinates': [-87.67635598...",NaN,NaN
4,70a8b3ab6335b5931e34c765a1aa35ef1b3a5999,f892614bf893b49cba778a71b629054fe7bf5ebad54364...,2026-01-15T23:45:00.000,2026-01-16T00:00:00.000,665,4.31,76,76,39,5.92,0,0,45.42,Credit Card,Globe Taxi,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",NaN,NaN

In [43]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19310 entries, 0 to 19309
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     19310 non-null  object
 1   taxi_id                     19310 non-null  object
 2   trip_start_timestamp        19310 non-null  object
 3   trip_end_timestamp          19310 non-null  object
 4   trip_seconds                19309 non-null  object
 5   trip_miles                  19310 non-null  object
 6   pickup_community_area       18710 non-null  object
 7   dropoff_community_area      17793 non-null  object
 8   fare                        19289 non-null  object
 9   tips                        19289 non-null  object
 10  tolls                       19289 non-null  object
 11  extras                      19289 non-null  object
 12  trip_total                  19289 non-null  object
 13  payment_type                19310 non-null  object
 14  company                     19310 non-null  object
 15  pickup_centroid_latitude    18712 non-null  object
 16  pickup_centroid_longitude   18712 non-null  object
 17  pickup_centroid_location    18712 non-null  object
 18  dropoff_centroid_latitude   17817 non-null  object
 19  dropoff_centroid_longitude  17817 non-null  object
 20  dropoff_centroid_location   17817 non-null  object
 21  pickup_census_tract         9119 non-null   object
 22  dropoff_census_tract        8909 non-null   object
dtypes: object(23)
memory usage: 3.4+ MB

In [44]:
taxi_trips.describe()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
count,19310,19310,19310,19310,19309,19310,18710,17793,19289,19289,19289,19289,19289,19310,19310,18712,18712,18712,17817,17817,17817,9119,8909
unique,19310,2073,96,107,3327,2274,77,76,2425,1038,32,184,3241,8,30,152,152,152,182,182,182,75,109
top,68bfc5ca3809fb9713c19f74a21f008b0e73fc49,008dda45db57cb6daa679a86ce8c8149ddc05446d545b1...,2026-01-15T17:00:00.000,2026-01-15T18:00:00.000,0,0,8,8,9.5,0,0,0,3.25,Mobile,Flash Cab,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",17031839100,17031839100
freq,1,52,400,400,200,1166,4785,4934,757,11341,19149,15225,305,7402,3911,1900,1900,1900,1594,1594,1594,1390,1585

In [45]:
taxi_trips[taxi_trips["fare"].isna()].sample(5)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,pickup_census_tract,dropoff_census_tract
11738,1ed84a74c4393b6e6ee4a317b6bd84a5e4147253,0044e6c0d091476299b99345501f756b23632a96cbaf40...,2026-01-15T12:45:00.000,2026-01-15T12:45:00.000,605,5.26,10,76,NaN,NaN,NaN,NaN,NaN,Cash,Chicago Independents,41.985015101,-87.804532006,"{'type': 'Point', 'coordinates': [-87.80453200...",41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",NaN,NaN
9314,fca9a6391d709601261f812de0044cad3d482361,c7e24b57c5ac5cc6b23bdaa7ad986c639f07680587bf71...,2026-01-15T14:45:00.000,2026-01-15T15:15:00.000,1927,2.26,28,28,NaN,NaN,NaN,NaN,NaN,Cash,5 Star Taxi,41.874005383,-87.66351755,"{'type': 'Point', 'coordinates': [-87.66351754...",41.874005383,-87.66351755,"{'type': 'Point', 'coordinates': [-87.66351754...",NaN,NaN
8073,f8823df7591bdb18fb0b023e304a53c13f24ff12,64fef3c62cbbc9dd8c00e7e1cf6d29ea73d9ebdd758d4f...,2026-01-15T15:45:00.000,2026-01-15T17:30:00.000,6625,19.43,76,8,NaN,NaN,NaN,NaN,NaN,Cash,5 Star Taxi,41.97907082,-87.903039661,"{'type': 'Point', 'coordinates': [-87.90303966...",41.89503345,-87.619710672,"{'type': 'Point', 'coordinates': [-87.61971067...",17031980000,17031081401
12200,41055d20dcca3549db65dbf7be28d308e315b88e,4c658dc5e7ea935f4c3bb9a3071f509efac3e99c93f6a6...,2026-01-15T12:15:00.000,2026-01-15T13:00:00.000,2949,10.06,8,3,NaN,NaN,NaN,NaN,NaN,Cash,Flash Cab,41.899602111,-87.633308037,"{'type': 'Point', 'coordinates': [-87.63330803...",41.96581197,-87.655878786,"{'type': 'Point', 'coordinates': [-87.65587878...",NaN,NaN
17457,b4c3cb2c1837253c8900ad4fda028121b51bec48,2407ff99e367ceb469a8cc6663e6ad6ec51fb0f401d370...,2026-01-15T07:45:00.000,2026-01-15T08:30:00.000,3429,13.35,76,6,NaN,NaN,NaN,NaN,NaN,Cash,Chicago Independents,41.980264315,-87.913624596,"{'type': 'Point', 'coordinates': [-87.91362459...",41.944226601,-87.655998182,"{'type': 'Point', 'coordinates': [-87.65599818...",NaN,NaN

#### Transformation: deal with NaN values

In [46]:
taxi_trips.drop(["pickup_census_tract", "dropoff_census_tract"], axis=1, inplace=True)

In [47]:
taxi_trips.drop(["pickup_centroid_location", "dropoff_centroid_location"], axis=1, inplace=True)

In [48]:
taxi_trips.dropna(inplace=True)

In [49]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17630 entries, 0 to 19309
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     17630 non-null  object
 1   taxi_id                     17630 non-null  object
 2   trip_start_timestamp        17630 non-null  object
 3   trip_end_timestamp          17630 non-null  object
 4   trip_seconds                17630 non-null  object
 5   trip_miles                  17630 non-null  object
 6   pickup_community_area       17630 non-null  object
 7   dropoff_community_area      17630 non-null  object
 8   fare                        17630 non-null  object
 9   tips                        17630 non-null  object
 10  tolls                       17630 non-null  object
 11  extras                      17630 non-null  object
 12  trip_total                  17630 non-null  object
 13  payment_type                17630 non-null  object
 14  company                     17630 non-null  object
 15  pickup_centroid_latitude    17630 non-null  object
 16  pickup_centroid_longitude   17630 non-null  object
 17  dropoff_centroid_latitude   17630 non-null  object
 18  dropoff_centroid_longitude  17630 non-null  object
dtypes: object(19)
memory usage: 2.7+ MB

#### Transformation: renaming

In [50]:
taxi_trips.rename(columns={"pickup_community_area": "pickup_community_area_id",
                           "dropoff_community_area": "dropoff_community_area_id"}, inplace=True)

In [51]:
taxi_trips.columns

Index(['trip_id', 'taxi_id', 'trip_start_timestamp', 'trip_end_timestamp',
       'trip_seconds', 'trip_miles', 'pickup_community_area_id',
       'dropoff_community_area_id', 'fare', 'tips', 'tolls', 'extras',
       'trip_total', 'payment_type', 'company', 'pickup_centroid_latitude',
       'pickup_centroid_longitude', 'dropoff_centroid_latitude',
       'dropoff_centroid_longitude'],
      dtype='object')

#### Transformation: create helper column for weather data

In [56]:
taxi_trips["trip_start_timestamp"] = pd.to_datetime(taxi_trips["trip_start_timestamp"])

In [57]:
taxi_trips["datetime_for_weather"] = taxi_trips["trip_start_timestamp"].dt.floor("h")

In [59]:
taxi_trips["datetime_for_weather"].unique()

<DatetimeArray>
['2026-01-15 23:00:00', '2026-01-15 22:00:00', '2026-01-15 21:00:00',
 '2026-01-15 20:00:00', '2026-01-15 19:00:00', '2026-01-15 18:00:00',
 '2026-01-15 17:00:00', '2026-01-15 16:00:00', '2026-01-15 15:00:00',
 '2026-01-15 14:00:00', '2026-01-15 13:00:00', '2026-01-15 12:00:00',
 '2026-01-15 11:00:00', '2026-01-15 10:00:00', '2026-01-15 09:00:00',
 '2026-01-15 08:00:00', '2026-01-15 07:00:00', '2026-01-15 06:00:00',
 '2026-01-15 05:00:00', '2026-01-15 04:00:00', '2026-01-15 03:00:00',
 '2026-01-15 02:00:00', '2026-01-15 01:00:00', '2026-01-15 00:00:00']
Length: 24, dtype: datetime64[ns]

#### Check: join taxi and weather data

In [60]:
current_datetime = datetime.now() - relativedelta(months=2)
formatted_datetime = current_datetime.strftime("%Y-%m-%d")

url = "https://archive-api.open-meteo.com/v1/era5"

params = {
    "latitude": 41.85,
    "longitude": -87.65,
    "start_date": formatted_datetime,
    "end_date": formatted_datetime,
    "hourly": "temperature_2m,wind_speed_10m,rain,precipitation"
}

response = requests.get(url, params=params)
data = response.json()

weather_data = {
    "datetime": data["hourly"]["time"],
    "teperature": data["hourly"]["temperature_2m"],
    "wind_speed": data["hourly"]["wind_speed_10m"],
    "rain": data["hourly"]["rain"],
    "percipitation": data["hourly"]["precipitation"]

}

weather_df = pd.DataFrame(weather_data)
weather_df["datetime"] = pd.to_datetime(weather_df["datetime"])


weather_df.head()

             datetime  teperature  wind_speed  rain  percipitation
0 2026-01-15 00:00:00        -6.2        25.8   0.0            0.0
1 2026-01-15 01:00:00        -6.6        25.2   0.0            0.0
2 2026-01-15 02:00:00        -6.8        25.2   0.0            0.0
3 2026-01-15 03:00:00        -7.1        24.6   0.0            0.0
4 2026-01-15 04:00:00        -7.3        23.5   0.0            0.0

In [62]:
taxi_trips_with_weather = taxi_trips.merge(weather_df, left_on="datetime_for_weather", right_on="datetime")

In [63]:
taxi_trips_with_weather.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather,datetime,teperature,wind_speed,rain,percipitation
0,68bfc5ca3809fb9713c19f74a21f008b0e73fc49,00c0020de20ee2cd36c1d41058360c24dad77a52639413...,2026-01-15 23:45:00,2026-01-15 23:45:00,1499,17.77,76,32,44,10.2,0,6.5,61.2,Credit Card,City Service,41.980264315,-87.913624596,41.878865584,-87.625192142,2026-01-15 23:00:00,2026-01-15 23:00:00,-6.3,9.2,0.0,0.0
1,6dfe66a61d223a34ec4d63ede02a9a01785549c5,8a0cbb4528e81a685396639a29b35d67d6d48bee0f6b96...,2026-01-15 23:45:00,2026-01-15 23:45:00,1320,15.4,56,7,38.75,5,0,4,47.75,Credit Card,Transit Administrative Center Inc,41.79259236,-87.769615453,41.922686284,-87.649488729,2026-01-15 23:00:00,2026-01-15 23:00:00,-6.3,9.2,0.0,0.0
2,6e4174f301ac0f53b3a26cbcb744592f908217f9,78d1ae230754ef2eca7aa3e828789bc4714b8a261a35d5...,2026-01-15 23:45:00,2026-01-15 23:45:00,7,0,8,8,20,0,0,0,20,Cash,City Service,41.899602111,-87.633308037,41.899602111,-87.633308037,2026-01-15 23:00:00,2026-01-15 23:00:00,-6.3,9.2,0.0,0.0
3,6f588976c6c141b981a629a94b50801d38e3b6c2,c9bda81f1aaad786527911c983b6be11f28c6f46469e1a...,2026-01-15 23:45:00,2026-01-15 23:45:00,658,2.44,8,24,9.37,2.54,0,0,12.41,Mobile,Taxicab Insurance Agency Llc,41.899602111,-87.633308037,41.901206994,-87.676355989,2026-01-15 23:00:00,2026-01-15 23:00:00,-6.3,9.2,0.0,0.0
4,70a8b3ab6335b5931e34c765a1aa35ef1b3a5999,f892614bf893b49cba778a71b629054fe7bf5ebad54364...,2026-01-15 23:45:00,2026-01-15 23:45:00,665,4.31,76,76,39,5.92,0,0,45.42,Credit Card,Globe Taxi,41.980264315,-87.913624596,41.980264315,-87.913624596,2026-01-15 23:00:00,2026-01-15 23:00:00,-6.3,9.2,0.0,0.0

#### Transformation: data type conversions

In [64]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17630 entries, 0 to 19309
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     17630 non-null  object
 1   taxi_id                     17630 non-null  object
 2   trip_start_timestamp        17630 non-null  datetime64[ns]
 3   trip_end_timestamp          17630 non-null  datetime64[ns]
 4   trip_seconds                17630 non-null  object
 5   trip_miles                  17630 non-null  object
 6   pickup_community_area_id    17630 non-null  object
 7   dropoff_community_area_id   17630 non-null  object
 8   fare                        17630 non-null  object
 9   tips                        17630 non-null  object
 10  tolls                       17630 non-null  object
 11  extras                      17630 non-null  object
 12  trip_total                  17630 non-null  object
 13  payment_type                17630 non-null  object
 14  company                     17630 non-null  object
 15  pickup_centroid_latitude    17630 non-null  object
 16  pickup_centroid_longitude   17630 non-null  object
 17  dropoff_centroid_latitude   17630 non-null  object
 18  dropoff_centroid_longitude  17630 non-null  object
 19  datetime_for_weather        17630 non-null  datetime64[ns]
dtypes: datetime64[ns](3), object(17)
memory usage: 2.8+ MB

In [65]:
taxi_trips_originial = taxi_trips.copy()

In [68]:
data_type = {
    "trip_end_timestamp": "datetime64[ns]",
    "trip_seconds": "int32",
    "trip_miles": "float",
    "pickup_community_area_id": "int8",
    "dropoff_community_area_id": "int8",
    "fare": "float",
    "tips": "float",
    "tolls": "float",
    "extras": "float",
    "trip_total": "float",
    "pickup_centroid_latitude": "float",
    "pickup_centroid_longitude": "float",
    "dropoff_centroid_latitude": "float",
    "dropoff_centroid_longitude": "float",
}

taxi_trips = taxi_trips.astype(data_type)

In [69]:
taxi_trips.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17630 entries, 0 to 19309
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     17630 non-null  object
 1   taxi_id                     17630 non-null  object
 2   trip_start_timestamp        17630 non-null  datetime64[ns]
 3   trip_end_timestamp          17630 non-null  datetime64[ns]
 4   trip_seconds                17630 non-null  int32
 5   trip_miles                  17630 non-null  float64
 6   pickup_community_area_id    17630 non-null  int8
 7   dropoff_community_area_id   17630 non-null  int8
 8   fare                        17630 non-null  float64
 9   tips                        17630 non-null  float64
 10  tolls                       17630 non-null  float64
 11  extras                      17630 non-null  float64
 12  trip_total                  17630 non-null  float64
 13  payment_type                17630 non-null  object
 14  company                     17630 non-null  object
 15  pickup_centroid_latitude    17630 non-null  float64
 16  pickup_centroid_longitude   17630 non-null  float64
 17  dropoff_centroid_latitude   17630 non-null  float64
 18  dropoff_centroid_longitude  17630 non-null  float64
 19  datetime_for_weather        17630 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(10), int32(1), int8(2), object(4)
memory usage: 2.5+ MB

In [70]:
taxi_trips.describe()

,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather
count,17630,17630,17630.000000,17630.000000,17630.000000,17630.000000,17630.000000,17630.000000,17630.000000,17630.000000,17630.000000,17630.000000,17630.000000,17630.000000,17630.000000,17630
mean,2026-01-15 14:10:33.879750400,2026-01-15 14:10:33.879750400,1021.251617,4.864189,29.535508,23.367612,17.916474,2.033036,0.005837,0.799032,21.071793,41.899846,-87.677001,41.894177,-87.652360,2026-01-15 13:48:01.429381632
min,2026-01-15 00:00:00,2026-01-15 00:00:00,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,41.660136,-87.913625,41.660136,-87.913625,2026-01-15 00:00:00
25%,2026-01-15 10:00:00,2026-01-15 10:00:00,424.000000,0.992500,8.000000,8.000000,7.610000,0.000000,0.000000,0.000000,9.000000,41.879255,-87.663518,41.879255,-87.656306,2026-01-15 10:00:00
50%,2026-01-15 14:30:00,2026-01-15 14:30:00,713.000000,1.890000,28.000000,25.000000,10.500000,0.000000,0.000000,0.000000,12.500000,41.892508,-87.633308,41.892042,-87.633308,2026-01-15 14:00:00
75%,2026-01-15 18:00:00,2026-01-15 18:00:00,1321.000000,7.010000,32.000000,32.000000,24.827500,2.930000,0.000000,0.000000,27.000000,41.922686,-87.626211,41.905858,-87.626146,2026-01-15 18:00:00
max,2026-01-15 23:45:00,2026-01-15 23:45:00,65163.000000,106.190000,77.000000,77.000000,2500.000000,50.000000,22.500000,105.000000,2500.000000,42.009623,-87.534903,42.015934,-87.534903,2026-01-15 23:00:00
std,NaN,NaN,1290.758601,5.865169,23.442244,18.213130,30.200684,3.411027,0.223243,2.817840,31.936089,0.052814,0.095505,0.047991,0.055971,NaN

##### Memory usage

In [72]:
orig_mem = taxi_trips_originial.memory_usage(deep=True).sum()
opt_mem = taxi_trips.memory_usage(deep=True).sum()

reduction = (orig_mem - opt_mem) / orig_mem * 100

print(f"Original: {orig_mem:,} bytes")
print(f"Optimzed: {opt_mem:,} bytes")
print(f"Memory reduced by: {reduction:.2f}%")

Original: 19,913,300 bytes
Optimzed: 8,945,647 bytes
Memory reduced by: 55.08%

#### Sanity checks

In [73]:
taxi_trips[taxi_trips["trip_end_timestamp"] == taxi_trips["trip_end_timestamp"].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather
0,68bfc5ca3809fb9713c19f74a21f008b0e73fc49,00c0020de20ee2cd36c1d41058360c24dad77a52639413...,2026-01-15 23:45:00,2026-01-15 23:45:00,1499,17.77,76,32,44.00,10.20,0.0,6.5,61.20,Credit Card,City Service,41.980264,-87.913625,41.878866,-87.625192,2026-01-15 23:00:00
1,6dfe66a61d223a34ec4d63ede02a9a01785549c5,8a0cbb4528e81a685396639a29b35d67d6d48bee0f6b96...,2026-01-15 23:45:00,2026-01-15 23:45:00,1320,15.40,56,7,38.75,5.00,0.0,4.0,47.75,Credit Card,Transit Administrative Center Inc,41.792592,-87.769615,41.922686,-87.649489,2026-01-15 23:00:00
2,6e4174f301ac0f53b3a26cbcb744592f908217f9,78d1ae230754ef2eca7aa3e828789bc4714b8a261a35d5...,2026-01-15 23:45:00,2026-01-15 23:45:00,7,0.00,8,8,20.00,0.00,0.0,0.0,20.00,Cash,City Service,41.899602,-87.633308,41.899602,-87.633308,2026-01-15 23:00:00
3,6f588976c6c141b981a629a94b50801d38e3b6c2,c9bda81f1aaad786527911c983b6be11f28c6f46469e1a...,2026-01-15 23:45:00,2026-01-15 23:45:00,658,2.44,8,24,9.37,2.54,0.0,0.0,12.41,Mobile,Taxicab Insurance Agency Llc,41.899602,-87.633308,41.901207,-87.676356,2026-01-15 23:00:00
4,70a8b3ab6335b5931e34c765a1aa35ef1b3a5999,f892614bf893b49cba778a71b629054fe7bf5ebad54364...,2026-01-15 23:45:00,2026-01-15 23:45:00,665,4.31,76,76,39.00,5.92,0.0,0.0,45.42,Credit Card,Globe Taxi,41.980264,-87.913625,41.980264,-87.913625,2026-01-15 23:00:00
5,816f93d526032ad501c1c36eff7c9c1f66d9d504,7d8179131ea9952793af4cda8635e94b56c2b92d3c376c...,2026-01-15 23:45:00,2026-01-15 23:45:00,1544,18.70,56,3,46.25,10.15,0.0,4.0,60.90,Credit Card,Flash Cab,41.792592,-87.769615,41.965812,-87.655879,2026-01-15 23:00:00
6,835e39b1b1b1a8a64d6086eeecfd0a4dd0b5aa78,813f13e9ed00615788ec81497e9585ef6ae4993a4491b8...,2026-01-15 23:45:00,2026-01-15 23:45:00,253,1.21,6,5,6.00,0.00,0.0,0.0,6.00,Cash,5 Star Taxi,41.944227,-87.655998,41.947792,-87.683835,2026-01-15 23:00:00
7,8de19bef86308315ccaa2884872e87a933123fd0,8e7bc3f66f8ce2c496e560d9d79d6851f1a2d7e6f8a88a...,2026-01-15 23:45:00,2026-01-15 23:45:00,240,0.50,8,8,5.92,0.00,0.0,0.0,5.92,Credit Card,Transit Administrative Center Inc,41.899602,-87.633308,41.899602,-87.633308,2026-01-15 23:00:00
9,97efd47d6b7651eacdd710bd3b3fb541c031d3b8,2b35ab2108b3fac599b7123c729632c4df95b70bab75e4...,2026-01-15 23:45:00,2026-01-15 23:45:00,1320,16.60,76,28,41.50,8.00,0.0,4.0,53.50,Credit Card,Transit Administrative Center Inc,41.980264,-87.913625,41.874005,-87.663518,2026-01-15 23:00:00
10,a1b2251a4efae0d47ca663d9551c1ddbf47501b7,26a53f41b40ca4ec225a15ff55054c0a2d9e4a48341ce9...,2026-01-15 23:45:00,2026-01-15 23:45:00,1140,16.80,76,8,40.75,9.05,0.0,4.0,53.80,Credit Card,Transit Administrative Center Inc,41.980264,-87.913625,41.899602,-87.633308,2026-01-15 23:00:00
11,a1e455a329104fea31577039ec7c67f1f1f11dc1,a4aa774267d068ec480649bab24c35ae8ea10b6149a81b...,2026-01-15 23:45:00,2026-01-15 23:45:00,800,7.81,32,3,21.04,3.97,0.0,0.0,25.51,Mobile,Sun Taxi,41.878866,-87.625192,41.965812,-87.655879,2026-01-15 23:00:00
13,a36b22e22eea03356d0d7c9fbbbb7861dfb697b7,687e4d96be3cc961be4ce4608d2ad3bfadf54e3bbe80d7...,2026-01-15 23:45:00,2026-01-15 23:45:00,465,2.02,24,24,9.51,0.00,0.0,0.0,10.01,Mobile,City Service,41.901207,-87.676356,41.901207,-87.676356,2026-01-15 23:00:00
14,a9ee15f71970df881780c058a52474df39942bf1,3f2a24e813695ce63232d6cccfc688ad3875df09b609fa...,2026-01-15 23:45:00,2026-01-15 23:45:00,540,1.60,8,32,8.25,2.00,0.0,0.0,10.25,Credit Card,Chicago City Taxi Association,41.899602,-87.633308,41.878866,-87.625192,2026-01-15 23:00:00
15,abf0c4c8dbe632483e2cbf1d36b71a9e60f2475a,e9cbe4386292ef926c573c0eefa3a1aa0b1448df6e19f0...,2026-01-15 23:45:00,2026-01-15 23:45:00,620,2.35,24,8,11.32,0.00,0.0,0.0,11.82,Mobile,Flash Cab,41.901207,-87.676356,41.899602,-87.633308,2026-01-15 23:00:00
16,b10a727f5539423121147833a380287fb66350dd,3e0ecc411309f519aa2278ee885227cde56891acadc652...,2026-01-15 23:45:00,2026-01-15 23:45:00,1282,11.90,76,4,31.00,8.88,0.0,4.0,44.38,Credit Card,Flash Cab,41.980264,-87.913625,41.975171,-87.687516,2026-01-15 23:00:00
18,b6d99a646fffb8334bc49eae9f2175561196074a,dd38b7cebd5414ae2b17595c68048ff8745c5147487c6c...,2026-01-15 23:45:00,2026-01-15 23:45:00,1140,6.90,28,6,21.71,0.00,0.0,0.0,21.71,Credit Card,Transit Administrative Center Inc,41.874005,-87.663518,41.944227,-87.655998,2026-01-15 23:00:00
19,b7f8fbfebffad9fe573594708d313c2079b06537,1d9f1ab92fd36a4578d77d25eecb75771962aa5047119a...,2026-01-15 23:45:00,2026-01-15 23:45:00,1390,9.23,60,70,38.45,0.00,0.0,0.0,38.45,Cash,Flash Cab,41.836150,-87.648788,41.745758,-87.708366,2026-01-15 23:00:00
20,c49577e99a16327d4a3a2f7184965ed70a68f1c1,eead1e2c21b26570411277cb384d3d8d072fc6da913b06...,2026-01-15 23:45:00,2026-01-15 23:45:00,1517,13.67,76,6,35.50,6.00,0.0,4.0,46.00,Credit Card,5 Star Taxi,41.980264,-87.913625,41.944227,-87.655998,2026-01-15 23:00:00
21,c991ed4d88300f1cbbf1e6260264a1aaa4876a39,df78a9555ae5e9041d230bb2f8e1ed8386a1a2a6e52baa...,2026-01-15 23:45:00,2026-01-15 23:45:00,1260,16.20,76,8,39.75,11.05,0.0,4.0,54.80,Credit Card,Chicago City Taxi Association,41.980264,-87.913625,41.899602,-87.633308,2026-01-15 23:00:00
22,cc4e9597ee880206104b3b5b4b4d8c277a2e9617,1f041942ef7c61fea34c62c89aea8231e4277ca158d54e...,2026-01-15 23:45:00,2026-01-15 23:45:00,1257,11.75,28,46,38.45,0.00,0.0,0.0,38.45,Cash,Flash Cab,41.874005,-87.663518,41.741243,-87.551428,2026-01-15 23:00:00
23,cfc659ab21dfd8720aad5d317b34715ac2f984f2,6834529dad6f57a5e4e090ebae5a902a2320ec7448e2b0...,2026-01-15 23:45:00,2026-01-15 23:45:00,1255,17.06,76,8,41.75,4.00,0.0,5.0,51.25,Credit Card,Taxicab Insurance Agency Llc,41.980264,-87.913625,41.899602,-87.633308,2026-01-15 23:00:00
24,cfdd3de3c00678a364b54c51c77d671a0d1dc1fd,396892a80daeabb209e6a8a53a4beb62d71771dcf69611...,2026-01-15 23:45:00,2026-01-15 23:45:00,603,3.02,28,8,25.00,5.10,0.0,0.0,30.60,Credit Card,Sun Taxi,41.874005,-87.663518,41.899602,-87.633308,2026-01-15 23:00:00
25,d176bb64507bdcbcd08f9fbabbc751f08cc30b17,f808a46257ac52d9b4a8d9df32feaf63b10542702ce653...,2026-01-15 23:45:00,2026-01-15 23:45:00,2700,20.20,28,32,49.50,0.00,0.0,0.0,49.50,Cash,Transit Administrative Center Inc,41.874005,-87.663518,41.878866,-87.625192,2026-01-15 23:00:00
27,dff1992c05ac40e38de21a1e2d2e7274ba6a46d0,0996793cf5fd9c72087b8d7fb941ba2f54c51573885d44...,2026-01-15 23:45:00,2026-01-15 23:45:00,1452,13.91,56,22,35.25,8.15,0.0,5.0,48.90,Credit Card,Flash Cab,41.792592,-87.769615,41.922761,-87.699155,2026-01-15 23:00:00
28,e0375dee4a05fb91fa87d10ea9a7c9ad03e144b7,7e4ec40f6fb2984cc6eccd671b1518c60af86dbf761df6...,2026-01-15 23:45:00,2026-01-15 23:45:00,519,3.88,8,6,14.52,0.00,0.0,0.0,15.02,Mobile,Taxicab Insurance Agency Llc,41.899602,-87.633308,41.944227,-87.655998,2026-01-15 23:00:00
29,e5ceb0488793797f688636c36ba8eb51dd202c0f,9438f1a06c0b15e97ee8f916f33494766f5d663d6273ca...,2026-01-15 23:45:00,2026-01-15 23:45:00,212,0.58,15,15,5.00,0.00,0.0,0.0,5.00,Cash,Flash Cab,41.954028,-87.763399,41.954028,-87.763399,2026-01-15 23:00:00
30,e880737cd27238897546729a70c1021a7b512a0b,4f78222d267c08ee7267810e5f3f2241dc61bf1396d036...,2026-01-15 23:45:00,2026-01-15 23:45:00,300,0.00,8,7,15.25,0.00,0.0,0.0,15.25,Cash,Taxicab Insurance Agency LLC,41.899602,-87.633308,41.922686,-87.649489,2026-01-15 23:00:00
31,e9d4540ff92b436da51f03ff37ca000383c054eb,b587d7b411523ec3634b1f20e09baf59d90c74d746c8a0...,2026-01-15 23:45:00,2026-01-15 23:45:00,692,4.33,8,6,13.75,3.56,0.0,0.0,17.81,Credit Card,Wolley Taxi,41.899602,-87.633308,41.944227,-87.655998,2026-01-15 23:00:00
32,eb188cc7963654f618b30bb97d7376ef68dc21e5,c84c28526a906ef1ad0ea7dc570f97949ecf92dfe156cb...,2026-01-15 23:45:00,2026-01-15 23:45:00,301,1.52,29,26,7.80,0.00,0.0,0.0,8.30,Mobile,Globe Taxi,41.860190,-87.717220,41.878594,-87.730232,2026-01-15 23:00:00
33,ed997e466721c108b71611221d86685e2cce903a,f07a57e895784bd00e38847f25ebf6c1964e28f0e83cc3...,2026-01-15 23:45:00,2026-01-15 23:45:00,825,3.22,28,8,14.60,0.00,0.0,0.0,15.10,Mobile,Medallion Leasin,41.874005,-87.663518,41.899602,-87.633308,2026-01-15 23:00:00
34,ef6a698eb79a4610fed503c7a0d4fd106fd4e268,ff31006332ba8816d747b0d2e002d6aaf4187fd1f3728c...,2026-01-15 23:45:00,2026-01-15 23:45:00,118,0.68,16,16,4.75,0.00,0.0,0.0,4.75,Cash,5 Star Taxi,41.953582,-87.723452,41.953582,-87.723452,2026-01-15 23:00:00
35,f145f5cc716acbbd3a6be69d0d1e48130bce39ee,5cdde36a39ded2651da1686c7813baf589dac6eb873894...,2026-01-15 23:45:00,2026-01-15 23:45:00,1320,17.40,76,28,42.50,9.50,0.0,4.5,56.50,Credit Card,Transit Administrative Center Inc,41.980264,-87.913625,41.874005,-87.663518,2026-01-15 23:00:00
36,f3117079841395bb9d1e77035c3a797a7bba5d00,f35fcc7d28fd3ca0324ad6b42c6bf1dd0413320a9c4b65...,2026-01-15 23:45:00,2026-01-15 23:45:00,462,1.38,77,77,7.74,0.00,0.0,0.0,8.24,Mobile,Medallion Leasin,41.986712,-87.663416,41.986712,-87.663416,2026-01-15 23:00:00
38,fa2925d4d24df71323b379808a9c52439d05b9bd,13211c2747462616a339ca520978b83ccd7fe5c490b860...,2026-01-15 23:45:00,2026-01-15 23:45:00,300,0.00,28,28,30.00,6.10,0.0,0.0,36.10,Credit Card,Transit Administrative Center Inc,41.874005,-87.663518,41.874005,-87.663518,2026-01-15 23:00:00
39,fe585ef83966b95059ce0ac3f435b820e956395a,9438f1a06c0b15e97ee8f916f33494766f5d663d6273ca...,2026-01-15 23:45:00,2026-01-15 23:45:00,237,0.89,15,15,5.25,0.00,0.0,0.0,5.25,Cash,Flash Cab,41.954028,-87.763399,41.954028,-87.763399,2026-01-15 23:00:00
40,62c6ff24ddf392f01609d3b12c3fa0fecde9bc25,6ef77e0e0e6d4b22a9c6f730b294a0b604c92cd43d557b...,2026-01-15 23:45:00,2026-01-15 23:45:00,1440,11.50,32,71,31.00,0.00,0.0,0.0,31.00,Unknown,Transit Administrative Center Inc,41.878866,-87.625192,41.744205,-87.656306,2026-01-15 23:00:00
41,5c7d1a10ed007dd9612b693d6714b9ddfec2cbd7,78d1ae230754ef2eca7aa3e828789bc4714b8a261a35d5...,2026-01-15 23:45:00,2026-01-15 23:45:00,10,0.00,8,8,3.25,0.00,0.0,0.0,3.25,Cash,City Service,41.899602,-87.633308,41.899602,-87.633308,2026-01-15 23:00:00
42,5915996a4324c4042d203dd8cddab7169b479ebe,8d75a4e15682364840d85e0f9f954e98b2703f4e252e88...,2026-01-15 23:45:00,2026-01-15 23:45:00,1140,13.80,76,7,34.25,7.00,0.0,4.0,45.25,Credit Card,Transit Administrative Center Inc,41.980264,-87.913625,41.922686,-87.649489,2026-01-15 23:00:00
43,526384fb1ffa4df87a0b5fc8dec04313a1df5c11,821fbe209557c784dcfc8435cd37ca5777c46f71219dac...,2026-01-15 23:45:00,2026-01-15 23:45:00,1455,4.56,8,6,18.25,0.00,0.0,0.0,18.25,Cash,City Service,41.899602,-87.633308,41.944227,-87.655998,2026-01-15 23:00:00
44,4c5c30d39ce5f3f88f7103e63e10ad45aa6a5485,7cb607b940a690e65b20dec20182d2646d3306f725130c...,2026-01-15 23:45:00,2026-01-15 23:45:00,1757,18.00,76,8,45.00,12.62,0.0,5.0,63.12,Credit Card,Globe Taxi,41.980264,-87.913625,41.899602,-87.633308,2026-01-15 23:00:00
45,4645a4c6fb9deb8cabf909781aa55c3d7912e1e8,dd49823dc32cc1ab686ed5873c2652d7bc1ffde6aac7cc...,2026-01-15 23:45:00,2026-01-15 23:45:00,431,3.13,61,35,12.81,0.00,0.0,0.0,13.31,Mobile,Medallion Leasin,41.809018,-87.659167,41.835118,-87.618678,2026-01-15 23:00:00
46,3bb1f52a40712a0d17b550b24ef734dc6e2bccc4,6fe3a00b45ce19e32d13df6abf236857b542db5a6bfed7...,2026-01-15 23:45:00,2026-01-15 23:45:00,615,2.85,7,28,11.05,0.00,0.0,0.0,11.55,Mobile,Flash Cab,41.922686,-87.649489,41.874005,-87.663518,2026-01-15 23:00:00
47,3a0f13900a22d72d224de007f1b10b0dd0e56b1e,0bea3de3c36237d68b009b24ee3db86c78e9e618a73a3b...,2026-01-15 23:45:00,2026-01-15 23:45:00,2100,16.60,56,6,44.75,13.55,0.0,9.0,67.30,Credit Card,Transit Administrative Center Inc,41.792592,-87.769615,41.944227,-87.655998,2026-01-15 23:00:00
48,34baa589f04ae806071f926ebb3212f0cbd9393e,a548c63608ec50e02a2311a0b6b1b2274995e3637ccb4c...,2026-01-15 23:45:00,2026-01-15 23:45:00,289,0.63,7,7,8.50,0.00,0.0,0.0,9.00,Mobile,City Service,41.922686,-87.649489,41.922686,-87.649489,2026-01-15 23:00:00
49,31a8fb01dd514a6ca79ea1e7a5aa5310897736f4,008dda45db57cb6daa679a86ce8c8149ddc05446d545b1...,2026-01-15 23:45:00,2026-01-15 23:45:00,360,0.97,6,6,6.08,0.00,0.0,0.0,6.58,Mobile,Taxicab Insurance Agency Llc,41.944227,-87.655998,41.944227,-87.655998,2026-01-15 23:00:00
50,2f3f96c2625d4ee4ab36b65f1f90887b5d1ba14c,bc38e7a06ef6fb44cebc048a2ee5b95e4895317666910e...,2026-01-15 23:45:00,2026-01-15 23:45:00,1620,14.70,56,6,37.25,10.75,0.0,16.0,64.00,Credit Card,Transit Administrative Center Inc,41.792592,-87.769615,41.944227,-87.655998,2026-01-15 23:00:00
51,2d3faacc6b03a5b53491081809b19127eaeac3f8,8195103b539d970548a1674c838870eaca8e1237aca990...,2026-01-15 23:45:00,2026-01-15 23:45:00,1553,14.60,76,6,37.50,9.60,0.0,10.0,57.60,Credit Card,Flash Cab,41.980264,-87.913625,41.944227,-87.655998,2026-01-15 23:00:00
52,272bfa29ce536dd58ff66515a3cdde2cd2bb6f04,9b48ad5744e86450fb4db78e7095a6827bafc43a6a9d9a...,2026-01-15 23:45:00,2026-01-15 23:45:00,132,0.47,6,6,4.50,3.00,0.0,0.0,8.00,Credit Card,Sun Taxi,41.944227,-87.655998,41.944227,-87.655998,2026-01-15 23:00:00
53,2074a03a931a4544f3d7588c1706fcc6442a02b8,7004f9dda1b1804fae67792a4c71bb326246b6266451a6...,2026-01-15 23:45:00,2026-01-15 23:45:00,956,10.42,76,14,27.00,6.50,0.0,5.0,39.00,Credit Card,Taxicab Insurance Agency Llc,41.980264,-87.913625,41.968069,-87.721559,2026-01-15 23:00:00
54,1d7ea2d4757555016a3a9c38293f166484147c38,b77a2dcc078698ea493d4d703014076e4272dc7d8b420e...,2026-01-15 23:45:00,2026-01-15 23:45:00,1320,16.60,76,8,40.75,8.95,0.0,4.0,53.70,Credit Card,Transit Administrative Center Inc,41.980264,-87.913625,41.899602,-87.633308,2026-01-15 23:00:00
55,1c2e2a2c7dfb7722341e5857e3210b1c9418f856,b3d64534f81ff06a34ae1001f3f6e3831011fb0f7a6f40...,2026-01-15 23:45:00,2026-01-15 23:45:00,1334,3.38,76,76,15.50,0.00,0.0,0.0,15.50,Cash,Taxicab Insurance Agency Llc,41.980264,-87.913625,41.980264,-87.913625,2026-01-15 23:00:00
57,115da5bd4e975f6814faea14d1748d8476cc1378,d5c821e78bf25431862f40219794e4d023679198afeb74...,2026-01-15 23:45:00,2026-01-15 23:45:00,712,7.24,8,77,20.00,0.00,0.0,0.0,20.00,Cash,Taxicab Insurance Agency Llc,41.899602,-87.633308,41.986712,-87.663416,2026-01-15 23:00:00
58,0ce586af51ebbd8f059e5543c016568ece3759ce,b56d49bc42507f35096478dd9613ed6aa7978739e34a99...,2026-01-15 23:45:00,2026-01-15 23:45:00,765,5.93,76,9,17.50,7.00,0.0,5.0,30.00,Credit Card,City Service,41.980264,-87.913625,42.007613,-87.813781,2026-01-15 23:00:00
59,0c9dedbf0892c13044af4a79c9981b2b76e39526,397fda5f3737a7b1a8ee587706ebb7e2ba198216728b26...,2026-01-15 23:45:00,2026-01-15 23:45:00,233,0.45,8,8,4.75,2.00,0.0,3.0,10.25,Credit Card,Globe Taxi,41.892042,-87.631864,41.892042,-87.631864,2026-01-15 23:00:00
62,027720e3f4355e4786e2658d8099988b663451a7,ca2e49fc5f32316d5c59cabe4993d8f7b27ee126bc5058...,2026-01-15 23:45:00,2026-01-15 23:45:00,420,1.00,8,8,8.16,0.00,0.0,0.0,8.16,Credit Card,Transit Administrative Center Inc,41.899602,-87.633308,41.899602,-87.633308,2026-01-15 23:00:00
63,003c3989396f57b3fe913fa9269e68a433367961,db3d7dbdc135e7fe12b5b92e1eee281d85025028652bc7...,2026-01-15 23:45:00,2026-01-15 23:45:00,2518,13.54,56,8,40.25,9.15,0.0,5.0,54.90,Credit Card,Blue Ribbon Taxi Association,41.792592,-87.769615,41.899602,-87.633308,2026-01-15 23:00:00

In [74]:
taxi_trips[taxi_trips["trip_seconds"] == taxi_trips["trip_seconds"].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather
256,b5fd08fec61010276c40f83d9f91e59b7964057d,75cf3a53aae5e5858361a7ca64f75d3407dc0a44d7bc42...,2026-01-15 23:00:00,2026-01-15 23:00:00,65163,3.5,4,77,13.5,0.0,0.0,0.0,13.5,Cash,Flash Cab,41.975171,-87.687516,41.986712,-87.663416,2026-01-15 23:00:00

In [75]:
taxi_trips[taxi_trips["fare"] == taxi_trips["fare"].max()]

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area_id,dropoff_community_area_id,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,datetime_for_weather
13563,eb6e3ee7d94c32cde2e024ff005eafc1f961fbcf,f19b6b38529c21e161c145c467760a5897eb378f4a8d75...,2026-01-15 10:45:00,2026-01-15 10:45:00,601,0.0,39,32,2500.0,0.0,0.0,0.0,2500.0,Cash,Tac - American United Dispatch,41.808916,-87.596183,41.878866,-87.625192,2026-01-15 10:00:00